modLoader="javafml"
loaderVersion="[47,)"
license="Yaxu Personal Use License 1.0"

[[mods]]
modId="realhanabimod"
version="1.0.0"
displayName="RealHanabiMod"
authors="you"
description='''
Forge 1.20.1 用の花火(打ち上げ花火)MOD。
花火打ち上げ機ブロックを設置し、右クリックでタイムラインGUIを開いて
色・大きさ・高さを自由に設定した花火ショーを作成・再生できる。
'''

[[dependencies.realhanabimod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.realhanabimod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
